// <auto-generated />
using System;
using KuaforYonetimSistemi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KuaforYonetimSistemi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KuaforYonetimSistemi.Models.Calisan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UygunSaatler")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Calisan");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdSoyad = "Ayşe Yılmaz",
                            UygunSaatler = "09:00-18:00"
                        },
                        new
                        {
                            Id = 2,
                            AdSoyad = "Fatma Kaya",
                            UygunSaatler = "10:00-17:00"
                        },
                        new
                        {
                            Id = 3,
                            AdSoyad = "Elif Demir",
                            UygunSaatler = "08:00-16:00"
                        },
                        new
                        {
                            Id = 4,
                            AdSoyad = "Zehra Çelik",
                            UygunSaatler = "12:00-20:00"
                        },
                        new
                        {
                            Id = 5,
                            AdSoyad = "Gizem Arslan",
                            UygunSaatler = "11:00-19:00"
                        });
                });

            modelBuilder.Entity("KuaforYonetimSistemi.Models.CalisanIslem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CalisanId")
                        .HasColumnType("int");

                    b.Property<int>("IslemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CalisanId");

                    b.HasIndex("IslemId");

                    b.ToTable("CalisanIslem");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CalisanId = 1,
                            IslemId = 1
                        },
                        new
                        {
                            Id = 2,
                            CalisanId = 1,
                            IslemId = 3
                        },
                        new
                        {
                            Id = 3,
                            CalisanId = 1,
                            IslemId = 6
                        },
                        new
                        {
                            Id = 4,
                            CalisanId = 2,
                            IslemId = 2
                        },
                        new
                        {
                            Id = 5,
                            CalisanId = 2,
                            IslemId = 4
                        },
                        new
                        {
                            Id = 6,
                            CalisanId = 2,
                            IslemId = 7
                        },
                        new
                        {
                            Id = 7,
                            CalisanId = 3,
                            IslemId = 1
                        },
                        new
                        {
                            Id = 8,
                            CalisanId = 3,
                            IslemId = 5
                        },
                        new
                        {
                            Id = 9,
                            CalisanId = 3,
                            IslemId = 8
                        },
                        new
                        {
                            Id = 10,
                            CalisanId = 4,
                            IslemId = 3
                        },
                        new
                        {
                            Id = 11,
                            CalisanId = 4,
                            IslemId = 9
                        },
                        new
                        {
                            Id = 12,
                            CalisanId = 5,
                            IslemId = 2
                        },
                        new
                        {
                            Id = 13,
                            CalisanId = 5,
                            IslemId = 4
                        },
                        new
                        {
                            Id = 14,
                            CalisanId = 5,
                            IslemId = 8
                        });
                });

            modelBuilder.Entity("KuaforYonetimSistemi.Models.Islem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sure")
                        .HasColumnType("int");

                    b.Property<decimal>("Ucret")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Islem");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Saç Kesimi",
                            Sure = 0,
                            Ucret = 50m
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Saç Boyama",
                            Sure = 0,
                            Ucret = 150m
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Fön Çekme",
                            Sure = 0,
                            Ucret = 30m
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Saç Bakımı",
                            Sure = 0,
                            Ucret = 120m
                        },
                        new
                        {
                            Id = 5,
                            Ad = "Perma",
                            Sure = 0,
                            Ucret = 200m
                        },
                        new
                        {
                            Id = 6,
                            Ad = "Manikür",
                            Sure = 0,
                            Ucret = 80m
                        },
                        new
                        {
                            Id = 7,
                            Ad = "Pedikür",
                            Sure = 0,
                            Ucret = 90m
                        },
                        new
                        {
                            Id = 8,
                            Ad = "Kaş Alma",
                            Sure = 0,
                            Ucret = 40m
                        },
                        new
                        {
                            Id = 9,
                            Ad = "Makyaj",
                            Sure = 0,
                            Ucret = 250m
                        });
                });

            modelBuilder.Entity("KuaforYonetimSistemi.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kullanici");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@example.com",
                            KullaniciAdi = "admin",
                            Rol = "Admin",
                            Sifre = "12345"
                        },
                        new
                        {
                            Id = 2,
                            Email = "fatma@example.com",
                            KullaniciAdi = "fatma",
                            Rol = "Kullanici",
                            Sifre = "12345"
                        },
                        new
                        {
                            Id = 3,
                            Email = "ahmet@example.com",
                            KullaniciAdi = "ahmet",
                            Rol = "Kullanici",
                            Sifre = "12345"
                        },
                        new
                        {
                            Id = 4,
                            Email = "elif@example.com",
                            KullaniciAdi = "elif",
                            Rol = "Kullanici",
                            Sifre = "12345"
                        },
                        new
                        {
                            Id = 5,
                            Email = "gizem@example.com",
                            KullaniciAdi = "gizem",
                            Rol = "Kullanici",
                            Sifre = "12345"
                        });
                });

            modelBuilder.Entity("KuaforYonetimSistemi.Models.Randevu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CalisanId")
                        .HasColumnType("int");

                    b.Property<int>("IslemId")
                        .HasColumnType("int");

                    b.Property<int>("IslemSuresi")
                        .HasColumnType("int");

                    b.Property<decimal>("Kazanc")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CalisanId");

                    b.HasIndex("IslemId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Randevu");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CalisanId = 1,
                            IslemId = 1,
                            IslemSuresi = 30,
                            Kazanc = 50m,
                            KullaniciId = 2,
                            Tarih = new DateTime(2024, 12, 11, 11, 17, 46, 452, DateTimeKind.Utc).AddTicks(8367)
                        },
                        new
                        {
                            Id = 2,
                            CalisanId = 2,
                            IslemId = 4,
                            IslemSuresi = 60,
                            Kazanc = 120m,
                            KullaniciId = 3,
                            Tarih = new DateTime(2024, 12, 12, 11, 17, 46, 452, DateTimeKind.Utc).AddTicks(8839)
                        },
                        new
                        {
                            Id = 3,
                            CalisanId = 3,
                            IslemId = 5,
                            IslemSuresi = 90,
                            Kazanc = 200m,
                            KullaniciId = 4,
                            Tarih = new DateTime(2024, 12, 13, 11, 17, 46, 452, DateTimeKind.Utc).AddTicks(8843)
                        },
                        new
                        {
                            Id = 4,
                            CalisanId = 4,
                            IslemId = 9,
                            IslemSuresi = 120,
                            Kazanc = 250m,
                            KullaniciId = 5,
                            Tarih = new DateTime(2024, 12, 14, 11, 17, 46, 452, DateTimeKind.Utc).AddTicks(8845)
                        });
                });

            modelBuilder.Entity("KuaforYonetimSistemi.Models.CalisanIslem", b =>
                {
                    b.HasOne("KuaforYonetimSistemi.Models.Calisan", "Calisan")
                        .WithMany("CalisanIslemler")
                        .HasForeignKey("CalisanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KuaforYonetimSistemi.Models.Islem", "Islem")
                        .WithMany("CalisanIslemler")
                        .HasForeignKey("IslemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calisan");

                    b.Navigation("Islem");
                });

            modelBuilder.Entity("KuaforYonetimSistemi.Models.Randevu", b =>
                {
                    b.HasOne("KuaforYonetimSistemi.Models.Calisan", "Calisan")
                        .WithMany()
                        .HasForeignKey("CalisanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KuaforYonetimSistemi.Models.Islem", "Islem")
                        .WithMany()
                        .HasForeignKey("IslemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KuaforYonetimSistemi.Models.Kullanici", "Kullanici")
                        .WithMany("Randevular")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calisan");

                    b.Navigation("Islem");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("KuaforYonetimSistemi.Models.Calisan", b =>
                {
                    b.Navigation("CalisanIslemler");
                });

            modelBuilder.Entity("KuaforYonetimSistemi.Models.Islem", b =>
                {
                    b.Navigation("CalisanIslemler");
                });

            modelBuilder.Entity("KuaforYonetimSistemi.Models.Kullanici", b =>
                {
                    b.Navigation("Randevular");
                });
#pragma warning restore 612, 618
        }
    }
}
